### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by ParkerMeyers** [baudneo/cync-lan#15]
**Describe the bug**
When trying to either run the cync-lan.py file to get the yaml file or to run it, a ValueError: invalid literal for int() with base 10: '' occurs.

**To Reproduce**
1. Follow installation instructions
2. Execute script to export cloud devices

**Expected behavior**
Expect the python file to run correctly and export the yaml file.

**Screenshots**
<img width="572" alt="Screenshot 2024-11-27 155305" src="https://github.com/user-attachments/assets/0a3b4f1a-6eb0-4ab5-bba2-c3434f1a6e5c">

**Desktop (please complete the following information):**
 - OS: Debian 12

**Comment by baudneo** [comment]
That's interesting, haven't seen a device throw that error while parsing version numbers.

Do you have any devices that aren't mains powered bulbs, plugs or switches? Like battery powered sensors? I'm assuming there is a non numeric string char in the firmware version reported by cync cloud. 

You can check firmware versions in the cync app device settings page manually as well:

# example of direct connect device
![Screenshot_20241127_143806](https://github.com/user-attachments/assets/46dc0295-5ba2-4025-8cba-32d1082ee2b3)


# example of bt only 'C by GE' device
![Screenshot_20241127_144133](https://github.com/user-attachments/assets/07db5366-ab1c-48ba-955e-18781736034f)

**Comment by ParkerMeyers** [comment]
Just bulbs and plugs, The only weird thing I can find with the version string is for the A19 soft white bulbs, the version reports as "3.8." and it is the latest version, I wonder if the "." at the end has to do with this?
![IMG_6253](https://github.com/user-attachments/assets/635f0002-3d2b-4b86-a083-db715c14a5b1)

**Comment by ParkerMeyers** [comment]
Interestingly, I just went around and made sure all the bulbs were updated and now I'm getting a new error (also having to do with the version)

```11/27/24 17:06:55.990 ERROR [cync-lan:4139] > main: Export failed: invalid literal for int() with base 10: '38\x00\x00\x00'
Traceback (most recent call last):
  File "/home/parke/cync-lan/cync-lan.py", line 4127, in <module>
    mesh_config = cloud_api.mesh_to_config(mesh_networks)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/parke/cync-lan/cync-lan.py", line 567, in mesh_to_config
    bulb_device = CyncDevice(
                  ^^^^^^^^^^^
  File "/home/parke/cync-lan/cync-lan.py", line 1008, in __init__
    self.version = fw_version
    ^^^^^^^^^^^^
  File "/home/parke/cync-lan/cync-lan.py", line 1037, in version
    self._version = int(value.replace(".", "").strip())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '38\x00\x00\x00'```

**Comment by baudneo** [comment]
I'll be home in roughly 45 mins and can take a look closer at the code. I may have fat fingered something. I'll try an export on my end and see if it throws that error. 

Shouldn't be too hard to get fixed this evening either way though.

**Comment by baudneo** [comment]
I didn't find an error regarding exporting firmware devices when I did it myself, I did find a different bug though, I am pushing code now to fix the bug I found and testing some strings to see if I can find the error you're having, should have a full fix and new images building soon.

**Comment by ParkerMeyers** [comment]
Perfect! thank you so much, i'm looking forward to the release!

**Comment by baudneo** [comment]
Ohhh, I didn't see the hex chars in the second error: `'38\x00\x00\x00'`. It seems that, that light and firmware is sending slightly different data packets. I saw this with the LED strip controller as well. What is the new firmware version for that light, `3.8.`? Can you add this to your docker compose:

```
    environment:
      CYNC_DEBUG: 1
      CYNC_RAW_DEBUG: 1
```

If you are not using docker, add it to your env vars using `export CYNC_RAW_DEBUG=1 CYNC_DEBUG=1`

The `38` is the version number, so it caught that but kept ingesting even after encountering 0x00, which isn't supposed to happen. The RAW data should give some insight into the payload structure.

**Comment by ParkerMeyers** [comment]
```
11/27/24 18:57:58.654 DEBUG [cync-lan:2067] > CyncLAN: reading devices from exported Cync config file...
Traceback (most recent call last):
  File "/root/cync-lan/cync-lan.py", line 3723, in <module>
    cync = CyncLAN(config_file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/cync-lan/cync-lan.py", line 2052, in __init__
    self.cfg_devices = self.parse_config(cfg_file)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/cync-lan/cync-lan.py", line 2112, in parse_config
    new_device = CyncDevice(
                 ^^^^^^^^^^^
  File "/root/cync-lan/cync-lan.py", line 955, in __init__
    self.version = fw_version
    ^^^^^^^^^^^^
  File "/root/cync-lan/cync-lan.py", line 983, in version
    self._version = int(value.replace('.','').strip())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
```

That is the error that is repeating in the logs with those env variables.
I also noticed that the mesh file has some devices that have (Unknown) firmware versions (without quotes), blank firmware versions (""), and there is one with a version that is not in quotes. Could this be causing any of this?

**Comment by ParkerMeyers** [comment]
Also, only some of the bulbs (even of the same time and version have the weird period at the end of the versions (eg: 3.8. instead of 3.8).

**Comment by ParkerMeyers** [comment]
![image](https://github.com/user-attachments/assets/9c17f588-cbe0-46ee-82e4-86d213a6b0f9)
There is also a few occurrences of the above in the firmware version string

**Comment by baudneo** [comment]
It does load the firmware version from the config file at first start, but when a device connects to cync-lan and sends a payload containing its firmware version, it tries to extract it from the hex data. What's in the exported YAML is extracted from the cloud data and converted from JSON to YAML. 

Can you take a look at the `raw_mesh.cync` file that was also exported? There is some identifying info in there, like the device ID, the first digits are your home ID and the last 3 digits are the device ID, so don't post the `raw_mesh.cync` data without sanitizing it first. What I am interested in seeing is the `firmwareVersion:` line in each device.

In `raw_mesh.cync`, search for `bulbsArray`. That has all the actual devices in each 'home'. Can you post what the value of `firmwareVersion` is for each device.

**Comment by baudneo** [comment]
Going to build images for a partial fix from commit https://github.com/baudneo/cync-lan/commit/be2ce77f3056ff08d33e5746c1da4fe652775d3c

May need fine-tuning if the cloud is sending hex. It accounts for empty strings and the `\0` data.

**Comment by baudneo** [comment]
Are things working now?

**Comment by LHVJoe** [comment]
This edit worked for me:

@version.setter
def version(self, value: Union[str, int]) -> None:
    if value in [None, 'Unknown', '']:
        logger.warning(f"Device {self.mac if hasattr(self, 'mac') else 'Unknown MAC'} has an invalid firmware version; setting to '0.0.1'.")
        self._version = "0.0.1"
        return

    if isinstance(value, int):
        self._version = str(value)
        return

    if isinstance(value, str):
        try:
            # Keep the version as a string directly
            cleaned_value = value.replace("\0", "").strip()
            self._version = cleaned_value
        except Exception as ex:
            logger.exception(f"Error processing firmware version '{value}': {ex}. Setting to '0.0.1'.")
            self._version = "0.0.1"
            
            
 Additionally - but unrelated -- I made these edits to handle some of my devices not mapping:
 
 type_2_str = {
    31: "C by GE Full Color A19 Bulb (BTLE only)",
    37: "Dimmer Switch with Motion and Ambient Light",
    42: "Reveal HD+ Smart Under Cabinet Light - 18 Inch",
    43: "Reveal HD+ Smart Under Cabinet Light - 24 Inch",
    68: "Indoor Direct Connect Plug",
    113: "Wire-Free White Temperature Dimmer Switch",
    133: "Full Color Direct Connect LED Light Strip Controller",
    137: "Full Color Direct Connect A19 Bulb",
    138: "Full Color Direct Connect BR30 Floodlight",
    140: "Full Color Direct Connect Outdoor PAR38 Floodlight",
    146: "Full Color Direct Connect Edison ST19 Bulb",
    147: "Full Color Direct Connect Edison G25 Bulb",
    148: "Dimmable Direct Connect Edison ST19 Bulb",

    224: "Direct Connect Thermostat",
}

    DeviceTypes: Dict[str, List[int]] = {
        "BULB": [31, 137, 146, 148],
        "SWITCH": [113],
        "BATTERY": [113],
        "DIMMER": [113],
        "STRIP": [133],
        "UNDERCABINET": [42, 43],
        "PLUG": [64, 65, 66, 67, 68],
        "EDISON": [146, 148],
        "THERMOSTAT": [224],
    }
